if __name__ == '__main__': 
    fd = open('C:\\Users\swapnil.machikar\OneDrive - Nihilent Limited\Desktop\Sample.txt')
    str1=fd.read(10).strip('\n\r')
    print("Read String is till 10       : ",str)
    pos= fd.tell()
    print("Current Position             : ",pos)
    str1=fd.read(10).strip('\n\r')
    print("Read String is till next 10  : ",str)
    pos= fd.tell()
    print("Current Position             : ",pos)
    print()
    print("Sending Pointer back to Top")
    pos = fd.seek(0,0)
    print("Current Position             : ",pos)
    str1=fd.read(25).strip('\n\r')
    print("Read String is till 25       : ",str)
    pos= fd.tell()
    print("Current Position             : ",pos)
    fd.close()